language: java

jdk:
  - oraclejdk8
  - oraclejdk7


before_install:
  - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.7.6.deb && sudo dpkg -i --force-confnew elasticsearch-1.7.6.deb
  - sudo java -version
  - sudo service elasticsearch start
  - sleep 30


script:
  - ulimit -a
  - mvn test
