language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7


before_install:
  - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.1.deb && sudo dpkg -i --force-confnew elasticsearch-1.4.1.deb --no-check-certificate

services:
  - elasticsearch


script:
  - ulimit -a
  - mvn test
