language: java

jdk:
  - oraclejdk8
  - openjdk7


script:
  - wget https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.5/elasticsearch-2.3.5.deb && sudo dpkg -i --force-confnew elasticsearch-2.3.5.deb
  - sudo /usr/share/elasticsearch/bin/plugin install delete-by-query
  - sudo service elasticsearch start
  - sleep 10
  - ulimit -a
  - mvn test
