language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6


before_install:
  - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.2.4.deb && sudo dpkg -i --force-confnew elasticsearch-1.4.1.deb

services:
  - elasticsearch


script:
  - mvn test